//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorporateWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Communication
    {
        public int CommunicationID { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Whatsapp { get; set; }
        public string Twitter { get; set; }
        public string Instagram { get; set; }
    }
}
