//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorporateWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Blog
    {
        public int BlogID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string PictureUrl { get; set; }
        public Nullable<int> Category_ID { get; set; }
    
        public virtual Tbl_Category Tbl_Category { get; set; }
    }
}
